"""Supabase(Postgres) 테이블 스키마 문서.

SQLAlchemy ORM 대신 Supabase REST 클라이언트(app/db/supabase_client.py)로 접근하므로
테이블은 SQL로 직접 관리한다 (Supabase SQL Editor에서 아래 DDL 실행):

    create table if not exists users (
      id bigint generated by default as identity primary key,
      login_id text unique,     -- 학생이 직접 정하는 고유 아이디(동명이인 문제 해결용)
      name text not null,
      grade int not null,
      created_at timestamptz not null default now()
    );

    create table if not exists attempts (
      id bigint generated by default as identity primary key,
      user_id bigint not null references users(id),
      problem_id text not null,
      unit text not null,
      difficulty text,          -- 쉬움 | 중간 | 어려움 (난이도별 정답률 집계용)
      hints_used int not null default 0,
      solved boolean not null default false,
      created_at timestamptz not null default now()
    );

unit_mastery는 별도 테이블로 두지 않고, attempts를 그때그때 집계해서 계산한다
(app/repositories/attempt_repo.py의 get_unit_mastery).
문제(problems) 데이터는 여전히 data/problems*.json으로 관리한다 (app/repositories/problem_repo.py).
"""
